Tutorial about Intro patterns
coq/platform-docs pull request #73
Opened 2024-12-23 22:47 UTC by thomas-lamiaux

A completion of #32

2024-12-24 11:19 UTC, Matafou commented on src/Tutorial_intro_patterns.v
> +    [intros ?X] is to be understood as "introduce exactly one variable".
The use of a question mark is a bit confusing isn't it? I first thought it was a syntactic thing.

2024-12-24 11:26 UTC, Matafou commented on src/Tutorial_intro_patterns.v
> +    than [ [a b ... d]]. The interrest is that it enables to preserves [let-in]
inteRest

2024-12-24 11:29 UTC, Matafou commented on src/Tutorial_intro_patterns.v
> +(** To help us do this, there is an intro pattern [?x/H] that introduce the
/ -> % ?

2024-12-24 11:31 UTC, Matafou commented
Nice tuto!

2024-12-24 15:20 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +    than [ [a b ... d]]. The interrest is that it enables to preserves [let-in]
Thanks. Btw, if you have never used it you should check out the code suggestion functionality. It enables to suggest a modification that I can later commit if I want. It is great to fix typos. It is this button

![image](https://github.com/user-attachments/assets/22b739d0-6b23-4726-be07-11373ca010b3)

2024-12-27 13:17 UTC, Tragicus reviewed
Nice work indeed. As a small optimization, you do not need `cbn` before `reflexivity`, since `reflexivity` unifies both sides of the equality, which reduces the terms as needed. I mostly checked for typos, should I also check the writing style?

2024-12-27 13:17 UTC, Tragicus commented on src/Tutorial_intro_patterns.v
> +(** We can then further combine it with rewrite patterns to simplify the proof:
```suggestion
(** We can then further combine this with rewrite patterns to simplify the proof: 
```

2024-12-27 13:17 UTC, Tragicus commented on src/Tutorial_intro_patterns.v
> +    matters in the end.
```suggestion
(** For a more involved example, consider the converse of the last example of section 3:
    if the concatenation of two lists has one element, then one list has one
    element and the other one is empty. 

    After pattern matching on [l1], we have an equality [a1::l1++l2 = [a]]. We
    must simplify it to [a1 = a] and [l1 ++ l2 = []] with [injection], then to
    [l1 = []] and [l2 = []] with [app_eq_nil], before being able to rewrite.
    This creates a lot of overhead as introduction and operations like
    destruction, simplification and rewriting have to be done separately.
    Furthermore, at every step we have to introduce fresh names that do not really
    matter in the end.
```

2024-12-27 13:17 UTC, Tragicus commented on src/Tutorial_intro_patterns.v
> +    This gives a much shorter proof without a bunch of fresh names.
```suggestion
(** Using intro patterns we can significantly shorten this proof and make it
    more intuitive, getting rid of tedious manipulations of hypotheses.

    We can use the intro pattern [[=]] to simplify the equality [a1::l1++l2 = [a]] 
    to [a1 = a] and [l1 ++ l2 = []]. We can then rewrite the first equality
    with [->], and simplify the second equality to [l1 = [] /\ l2 = []] thanks
    to [%app_eq_nil]. Finally, we can rewrite both equalities using [->], giving
    us the intro pattern [intros [= -> [-> ->]%app_eq_nil]].
    This yields a much shorter proof without a bunch of fresh names.
```

2024-12-27 14:46 UTC, thomas-lamiaux commented
@Tragicus Thanks for checking for typos. Most comes from refactoring. After staring at the code for so long you start not seeing them anymore and basic spell checker don't catch them. 

Concerning `cbn`I know it is not needed but for introductory contents I think it is important that people see the simplification to get what is going on.

2024-12-27 21:50 UTC, JoJoDeveloping commented on src/Tutorial_intro_patterns.v
> +    have one constructor with two arguments like [/\], then it is possible to
Perhaps you could explicitly add that these patterns also works with existential quantifiers?

2024-12-27 23:35 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +    have one constructor with two arguments like [/\], then it is possible to
It is a good idea, I will add it

2024-12-28 10:47 UTC, Villetaneuse reviewed
Nice work. I have some minor suggestions and a longer one (about nat).

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +    introduce the variables with [intros p & q & r & h] rather than by having to
```suggestion
    introduce the variables with [intros (p & q & r & h)] rather than by having to 
```
Maybe also add that it only applies to right-associative operators.

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +(** It is also very common to introduce an equality that we wish to later rewrite:
```suggestion
(** It is also very common to introduce an equality that we only wish to use once as a rewrite rule on the goal: 
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +
I think it would be useful to show a case analysis on something else than "or". Here is a suggestion for `nat`.
```suggestion
(** Using intro patterns is not at all restricted to logical formulas. Consider Peano's natural numbers
    (the type [nat] here. *)

Print nat.

(** It has two constructors, one called [O] without argument for the number zero and the successor
    function [S]. This says that any number of type [nat] is either 0 or the successor of another number
    of type [nat]. This can be used to reason by case analysis on (the nullity of) a natural number. *)

Goal forall (n : nat), n = 0 \/ (exists (m : nat), n = 1 + m).
Proof.
  intros n. destruct n as [| n']. (* two cases, the first one is empty because [O] has no argument. *)
  - left. reflexivity.
  - right. exists n'. reflexivity.
Qed.

(** Again, we can [intros] and [destruct] our [n] variable in one step. *)

Goal forall (n : nat), n = 0 \/ (exists (m : nat), n = 1 + m).
Proof.
  intros [| n']. (* two cases, the first one is empty because [O] has no argument. *)
  - left. reflexivity.
  - right. exists n'. reflexivity.
Qed.
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +  intros n m H. injection H. intros H'. rewrite H'. cbn. reflexivity.
```suggestion
Proof.
  intros n m H. injection H as H'. rewrite H'. cbn. reflexivity.
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +  intros n m [=]. rewrite H0. cbn. reflexivity.
```suggestion
Proof.
  intros n m [= H]. rewrite H. cbn. reflexivity.
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +  intros n m [= ->]. cbn. reflexivity.
```suggestion
Proof.
  intros n m [= ->]. cbn. reflexivity.
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +    variable [x] and applies the lemma [H] to it. We can hence write
Use more consistent names, here:
```suggestion
(** To help us do this, the [%] intro pattern [H%impl] introduces the
    hypothesis [H] and applies the implication [impl] in it. We can hence write 
```

2024-12-28 10:47 UTC, Villetaneuse commented on src/Tutorial_intro_patterns.v
> +  intros A l1 l2 a [[-> ->]| [-> ->]].
Consistent spaces between `|`:
```suggestion
  intros A l1 l2 a [[-> ->] | [-> ->]].
```

2024-12-28 15:48 UTC, LyesSaadi commented on src/Tutorial_intro_patterns.v
> +    names specified [x], [y], ..., [z], and fail if one of the names is already used.
Also, quick typo, this should probably be "fails" and not "fail" since it has the subject "It".

2024-12-28 16:19 UTC, LyesSaadi requested changes
Very good explanations which are easy to understand, and very pertinent examples. I frequently found myself asking for "hey, would we be able to combine this and that", only for an example of that to be given just afterward.

2024-12-28 16:19 UTC, LyesSaadi commented on src/Tutorial_intro_patterns.v
> +    do no appear dependently in the rest of the goal. In this example, it will
This explanation is quite hard to understand. Here, the way it is phrased with a negative and an adverb makes it unclear IMHO.
I would've written that as "[intros *] will only introduce variables from the goal, which are independent of previously introduced variables.".

2024-12-28 16:23 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +    [intros x y ... z] will introduce as many variables as mentioned with the
```suggestion
    [intros x y ... z] will introduce as many variables and hypotheses as mentioned with the 
```

2024-12-28 16:27 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +(** Another particularly useful way of simplifying an equality is to deduce the
```suggestion
(** Another particularly useful way of simplifying an equality is to deduce that the 
```

2024-12-28 16:28 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +    intro pattern [ [ x ... y | ... | z ... w ]. It enables to give a
```suggestion
    intro pattern [ [ x ... y | ... | z ... w ]]. It enables to give a 
```

2024-12-28 16:30 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +  intros P Q [].
I personally use it all the time when my proof are trivial enough and don't need names.
I think it is fine here as there is already a warning above

2024-12-28 16:30 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +
This suggestion is good but comes too late. I'll add it but earlier

2024-12-28 16:34 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +  intros P Q R [p [q r]].
@Villetaneuse  Can use code suggestion to suggest something somewhere ?
Same for the other example below ?

2024-12-28 16:41 UTC, thomas-lamiaux commented on src/Tutorial_intro_patterns.v
> +  intros P Q R [p [q r]].
You know what I'll just add parentheses.

2024-12-28 17:13 UTC, thomas-lamiaux commented
@Villetaneuse All is solved for one detail. In your suggestion you have introduced the `as ...` notation which uses intro patterns itself but without explanation, so I feel there is a bit of a loop. What do you think ?

2024-12-29 09:09 UTC, Villetaneuse commented
> @Villetaneuse All is solved for one detail. In your suggestion you have introduced the `as ...` notation which uses intro patterns itself but without explanation, so I feel there is a bit of a loop. What do you think ?

That's indeed an issue. However, I was thinking that the reader was already familiar with these forms for the `destruct` and `injection` tactics (even though she may ignore that there is an intro pattern after `as`).
That's what I do in my course.

As I see it, we can go in two directions:
- remove `as` in the beginning of this tutorial, use `case` instead of `destruct` to avoid auto names, or as you did before use `destruct` and do not use the auto names, and progressively introduce the `as` (almost) "tactical"
- rely on some previous experience with `destruct as`; we still can explain that in general `as` takes an intro pattern

What do you think?

Would you like that I extract from my course a tutorial about basic proofs of logical statements which could be a prerequisite, in order to have a clearer view?

2024-12-30 03:32 UTC, thomas-lamiaux commented
I think it is best to suppose people know destruct as and want to know about intro patterns, and to just add a comment.

> Would you like that I extract from my course a tutorial about basic proofs of logical statements which could be a prerequisite, in order to have a clearer view?

@Villetaneuse Sth that is a bit urgent to do, would be a learning game for Coq, an adaptation of the natural number game or sth else so that people can try it out

2024-12-30 09:28 UTC, Villetaneuse commented
> I think it is best to suppose people know destruct as and want to know about intro patterns, and to just add a comment.
> 

All right, I will add a remark and a list of tactics which allow `as intro_pattern` in the end.

> > Would you like that I extract from my course a tutorial about basic proofs of logical statements which could be a prerequisite, in order to have a clearer view?
> 
> @Villetaneuse Sth that is a bit urgent to do, would be a learning game for Coq, an adaptation of the natural number game or sth else so that people can try it out and learn the base.

If you really want something which resembles the natural number game, it's very difficult at this point, I'm afraid. We would first need a **stable** javascript backend and, to some extent, frontend.

2025-01-03 16:26 UTC, merged